### ISSUE TITLE
Target/Goal Field

### ISSUE THREAD

**Issue by amerryma** [ZeroGwafa/ArchMatCounter#2]
Could we get a spot where we can enter a target or goal materials? Then it shows the progress towards that goal better:

10 / 36

etc.

**Comment by ZeroGwafa** [comment]
I have this just about done.  Added since I was updating the UI design anyways.  Should be in the next release.

My plan is if you put in an amount in the (to be renamed "want") column, it will highlight the row in green once the Qty is greater than or equal to "Want"
![1SfF0fG82D](https://user-images.githubusercontent.com/12411847/78471892-9adc7300-7702-11ea-8f03-e02c3d8e1293.gif)
,

**Comment by ZeroGwafa** [comment]
Added with this release.
