### ISSUE TITLE
double counting materials

### ISSUE THREAD

**Issue by lunaras13** [ZeroGwafa/ArchMatCounter#23]
currently it checks the chat box every time there is a screen load and double counts those materials. for example if you just farmed 30 of something and want to teleport away, 5 of them are still in chat box so upon completion of the teleport it adds 5 to the total collected again.

perhaps some code to keep track of the last 10 collections including their time stamp and not allow it to count it a second time would work

currently the only fix is stopping the thing every time ur inventory gets full but that's the kind of hassle that defeats the purpose of using the app

**Comment by ZeroGwafa** [comment]
I may have a fix for this.  Did some refactoring (code needs a TON more love.  Silly past self).  

Testing it for a few hours, if everything looks good, i'll push the change.

Question:  Is there any trigger that grants multiple materials on the same tick?

**Comment by ExInferi** [comment]
> Question: Is there any trigger that grants multiple materials on the same tick?

![image](https://github.com/user-attachments/assets/98ae8285-41e1-4026-a0b9-6660d9b26495)
These ones came to mind to me: 
- **Fortune perk:** Doubling the material and reporting the material it doubled
- **Balarak's sash brush:** Doubling the material, but doesn't mention the material being doubled
- **Auto-screener v1.080:** As materials and soil can be obtained on the same tick, the auto-screener may also proc during the excavation of a material. 

All of these can theoretically even stack together. 

I've been using `sessionStorage` for preventing duplicates these days. You can check out [WildyRewards](https://github.com/ExInferi/WildyRewards) - a fork of a fork of a fork of SerenTracker, to see it in action.

**Comment by ZeroGwafa** [comment]
Ok, did a bit of refactoring here

- Now (properly) counts double materials for Fortune Perk
- Counts double mats for Balarak's Sash Brush
- Added a chatHistory (thanks @ExInferi for the protips!) to prevent loading screens/restarting the app from reading old lines, and adding mats.
- Bunch of under-the-hood changes that shouldn't affect the user experience.


**NOTE**
You will want to have at least 5 timestamps visible for the rare-but-can-happen of Fortune/Brush/Screener/Porters to be tracked properly.  Otherwise, there is a chance a material will be missed.
