### ISSUE TITLE
Hide/unhide mats when you import from the artifact calculator

### ISSUE THREAD

**Issue by Hoppingmad9** [ZeroGwafa/ArchMatCounter#5]
Hide mats that don't have a goal and unhide mats with a goal when importing from the artifact calculator

**Comment by ZeroGwafa** [comment]
I think the plan here is to go with:
1. Row's "Hide" box is checked, will always hide it no matter what.
2. If filter is checked:
  2a. Check if "Show Goals" is checked.  If it's checked, hide any row where "Qty" and "Goals" are 0.
  2b. Otherwise, hide any row where Qty = 0. 

I'll be working on this in the next day or so.

**Comment by ZeroGwafa** [comment]
This has been implemented.  If the material has a Qty set, or a Goal set, it will show when Filter is enabled, UNLESS the "hide" checkbox for that row is also checked.

Thanks!  Closing Issue.
